version: "3.11"

services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"

  litellm-proxy:
    build:
      context: .
      dockerfile: Dockerfile.lite
      args:
        target: runtime
    image: ghcr.io/berriai/litellm:main-stable
    #########################################
    ## Uncomment these lines to start proxy with a config.yaml file ##
    volumes:
      - ./config.yaml:/app/config.yaml
    ###############################################
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
        ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    env_file:
      - .env # Load local .env file