services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    ports:
      - "8888:8888"

  litellm-proxy:
    build:
      context: .
      dockerfile: Dockerfile.lite
      args:
        target: runtime
    volumes:
      - ./config.yaml:/app/config.yaml
    ports:
      - "4000:4000" # Map the container port to the host, change the host port if necessary
    environment:
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
    env_file:
      - .env # Load local .env file